CREATE TABLE Pacjent(
Id INT IDENTITY(1,1) PRIMARY KEY,
Imie NVARCHAR(50) NOT NULL,
Nazwisko NVARCHAR(50) NOT NULL,
Data_urodzenia DATE NOT NULL,
Miejsce_urodzenia NVARCHAR(50) NOT NULL,
PESEL NVARCHAR(11) NOT NULL UNIQUE
)